Animateur:
    type: entity
    table: animateur
    indexes:
        fk_animateur_user_idx:
            columns:
                - user_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: true
            length: 90
            fixed: false
            comment: ''
        prenom:
            type: string
            nullable: true
            length: 90
            fixed: false
            comment: ''
        dateNaissance:
            type: date
            nullable: true
            comment: ''
            column: date_naissance
        nomUtilisateur:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
            column: nom_utilisateur
        motDePasse:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
            column: mot_de_passe
        superviseurId:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: superviseur_id
    manyToOne:
        user:
            targetEntity: FosUserUser
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
