Demandechangementlicence:
    type: entity
    table: demandechangementlicence
    indexes:
        fk_demandechangementlicence_localisation_idx:
            columns:
                - localisation_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        licence:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
        motif:
            type: string
            nullable: true
            length: 200
            fixed: false
            comment: ''
    manyToOne:
        localisation:
            targetEntity: Localisation
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                localisation_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
