Marque:
    type: entity
    table: marque
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        libelle:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: ''
        enabled:
            type: boolean
            nullable: true
            comment: ''
    lifecycleCallbacks: {  }
