Parameters:
    type: entity
    table: parameters
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        key:
            type: string
            nullable: true
            length: 70
            fixed: false
            comment: ''
        value:
            type: string
            nullable: true
            length: 70
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
