Post:
    type: entity
    table: post
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: ''
        body:
            type: string
            nullable: true
            length: 400
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
