Rapport:
    type: entity
    table: rapport
    indexes:
        fk_rapport_cadeau_idx:
            columns:
                - cadeau_id
        fk_rapport_marqueachetee_idx:
            columns:
                - marqueachetee_id
        fk_rapport_marquehabituelle_idx:
            columns:
                - marquehabituelle_id
        fk_rapport_localisation_idx:
            columns:
                - localisation_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        achete:
            type: boolean
            nullable: true
            comment: ''
        trancheageId:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: trancheage_id
        raisonachatId:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: raisonachat_id
        raisonrefusId:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: raisonrefus_id
        sexe:
            type: string
            nullable: true
            length: 1
            fixed: false
            comment: ''
        fidelite:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
        marquehabituelleQte:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: marquehabituelle_qte
        marqueacheteeQte:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: marqueachetee_qte
        tombola:
            type: boolean
            nullable: true
            comment: ''
        commentaire:
            type: string
            nullable: true
            length: 350
            fixed: false
            comment: ''
        dateCreation:
            type: datetime
            nullable: true
            comment: ''
            column: date_creation
    manyToOne:
        cadeau:
            targetEntity: Cadeau
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                cadeau_id:
                    referencedColumnName: id
            orphanRemoval: false
        localisation:
            targetEntity: Localisation
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                localisation_id:
                    referencedColumnName: id
            orphanRemoval: false
        marqueachetee:
            targetEntity: Marque
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                marqueachetee_id:
                    referencedColumnName: id
            orphanRemoval: false
        marquehabituelle:
            targetEntity: Marque
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                marquehabituelle_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
