Superviseur:
    type: entity
    table: superviseur
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
        prenom:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
        dateNaissance:
            type: date
            nullable: true
            comment: ''
            column: date_naissance
        nomUtilisateur:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
            column: nom_utilisateur
        motDePasse:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
            column: mot_de_passe
    lifecycleCallbacks: {  }
