_webservice_authentification:
    pattern:  /webservice/authentification
    defaults: { _controller: AcmeDemoBundle:Webservice:authentification }

_webservice_getShelfShareData:
    pattern:  /webservice/getShelfShareData
    defaults: { _controller: AcmeDemoBundle:Webservice:getShelfShareData }

_tableauDeBoard:
    pattern:  /admin/app/tableauDeBoard
    defaults: { _controller: AcmeDemoBundle:Demo:tableauDeBoard }

_mapDashboard:
    pattern:  /admin/app/mapDashboard
    defaults: { _controller: AcmeDemoBundle:Demo:mapDashboard }

_statistics:
    pattern:  /admin/app/statistics
    defaults: { _controller: AcmeDemoBundle:Demo:statistics }

_toggleActivateTombola:
    pattern:  /admin/app/toggleActivateTombola
    defaults: { _controller: AcmeDemoBundle:Demo:toggleActivateTombola }

_generateXlsFileView:
    pattern:  /admin/app/generateXlsFileView
    defaults: { _controller: AcmeDemoBundle:Demo:generateXlsFileView }

_generateXlsFileExecute:
    pattern:  /admin/app/generateXlsFileExecute
    defaults: { _controller: AcmeDemoBundle:Demo:generateXlsFileExecute }

_uploadXlsFileForClientView:
    pattern:  /admin/app/uploadXlsFileForClientView
    defaults: { _controller: AcmeDemoBundle:Demo:uploadXlsFileForClientView }

_uploadXlsFileForClientExecute:
    pattern:  /admin/app/uploadXlsFileForClientExecute
    defaults: { _controller: AcmeDemoBundle:Demo:uploadXlsFileForClientExecute }

_custom_valider:
    pattern:  /admin/app/valider
    defaults: { _controller: AcmeDemoBundle:CRUD:valider }

_custom_devalider:
    pattern:  /admin/app/devalider
    defaults: { _controller: AcmeDemoBundle:CRUD:devalider }