_webservice_authentification:
    pattern:  /webservice/authentification
    defaults: { _controller: AcmeDemoBundle:Webservice:authentification }

_webservice_getShelfShareData:
    pattern:  /webservice/getShelfShareData
    defaults: { _controller: AcmeDemoBundle:Webservice:getShelfShareData }

_webservice_getSfosPerformanceData:
    pattern:  /webservice/getSfosPerformanceData
    defaults: { _controller: AcmeDemoBundle:Webservice:getSfosPerformanceData }

_webservice_getOutOfStockData:
    pattern:  /webservice/getOutOfStockData
    defaults: { _controller: AcmeDemoBundle:Webservice:getOutOfStockData }

_webservice_getRefencementProduits:
    pattern:  /webservice/getReferencementData
    defaults: { _controller: AcmeDemoBundle:Webservice:getReferencementData }

_webservice_saveRefencementProduits:
    pattern:  /saveReferencementData
    defaults: { _controller: AcmeDemoBundle:Webservice:saveReferencementData }

_tableauDeBoard:
    pattern:  /tableauDeBoard
    defaults: { _controller: AcmeDemoBundle:Demo:tableauDeBoard }

_referencement:
    pattern:  /referecement
    defaults: { _controller: AcmeDemoBundle:Demo:referencement }

_mapDashboard:
    pattern:  /mapDashboard
    defaults: { _controller: AcmeDemoBundle:Demo:mapDashboard }

_statistics:
    pattern:  /statistics
    defaults: { _controller: AcmeDemoBundle:Demo:statistics }

_toggleActivateTombola:
    pattern:  /toggleActivateTombola
    defaults: { _controller: AcmeDemoBundle:Demo:toggleActivateTombola }

_generateXlsFileView:
    pattern:  /generateXlsFileView
    defaults: { _controller: AcmeDemoBundle:Demo:generateXlsFileView }

_generateXlsFileExecute:
    pattern:  /generateXlsFileExecute
    defaults: { _controller: AcmeDemoBundle:Demo:generateXlsFileExecute }

_uploadXlsFileForClientView:
    pattern:  /uploadXlsFileForClientView
    defaults: { _controller: AcmeDemoBundle:Demo:uploadXlsFileForClientView }

_uploadXlsFileForClientExecute:
    pattern:  /uploadXlsFileForClientExecute
    defaults: { _controller: AcmeDemoBundle:Demo:uploadXlsFileForClientExecute }

_custom_valider:
    pattern:  /valider
    defaults: { _controller: AcmeDemoBundle:CRUD:valider }

_custom_devalider:
    pattern:  /devalider
    defaults: { _controller: AcmeDemoBundle:CRUD:devalider }
